### ISSUE TITLE
Is Tweet pre-processing needed?

### ISSUE THREAD

**Issue by sbwww** [xinyangz/TwHIN-BERT#1]
I notice that a previous work BERTweet uses a normalization of Tweets that translate emojis and URLs into specific tokens.
Since you have an emoji prediction task, I guess emojis are not just simply translated into a fixed token. Are they stored in the vocabulary as Unicode characters, or translated into fine-grained tokens? And, how are URLs tokenized, URLs can be sometimes long and meaningless, but sometimes informative.
I didn't find related descriptions in your paper, and I'd like to know if I need a pre-processing of Tweet before using TwHIN-BERT, or just feed a raw Tweet text into the model.

And, of course, thank you very much for the great multilingual pre-trained model!

**Comment by xinyangz** [comment]
We did not preprocess emojis and URLs. They are stored as unicode characters, the format you'd get from Twitter API. No preprocessing for tokenization is needed.

**Comment by sbwww** [comment]
Thank you for the reply!
